In [1]:
import numpy as np

import endocytosis.io.image.image_reader as image_reader
# import endocytosis.contrib.gohlke.tifffile as tifffile

In [2]:
path = r'D:\\endocytosis_data_subset\\2016-12-14 iso\\2016-12-14 Sp57 proto +050 001\\2016-12-14 Sp57 proto +050 001.tif'

In [3]:
# instantiate ImageReader
reader = image_reader.ImageReader()

In [4]:
# once load() method is executed, image data and metadata
# can be accessed via the data and metadata attributes, respectively
reader.load(path)

In [5]:
# image data is retrieved as np.ndarray via the request() method of the datasource
# arguments must be listed in c, t, z order

# single image
arg = (0, 10, 5)
print("shape: {}".format(reader.data.request(*arg).shape))
print("data: {}".format(reader.data.request(*arg)))

shape: (1024, 1024)
data: [[504 488 507 ... 469 511 491]
 [517 509 504 ... 496 487 472]
 [499 488 490 ... 481 481 475]
 ...
 [489 510 486 ... 484 469 484]
 [480 492 527 ... 486 503 514]
 [492 520 511 ... 505 512 494]]


In [6]:
# if no parameters are entered into the .request() method, 
# simply retrieve the last requested image
# (tifffile caches these images)
print("shape: {}".format(reader.data.request().shape))
print("data:\n{}".format(reader.data.request()))

shape: (1024, 1024)
data:
[[504 488 507 ... 469 511 491]
 [517 509 504 ... 496 487 472]
 [499 488 490 ... 481 481 475]
 ...
 [489 510 486 ... 484 469 484]
 [480 492 527 ... 486 503 514]
 [492 520 511 ... 505 512 494]]


In [13]:
# use a slice argument to get a stack of images
# currently only slicing in one dimension is supported
arg = (0, slice(10), 5)
print("shape: {}".format(reader.data.request(*arg).shape))
print("data:\n{}".format(reader.data.request(*arg)))
tif_page_numbers = reader.data._request(0, slice(20), 5)[0]
print("page indices: {}".format(", ".join(map(str, tif_page_numbers))))

shape: (10, 1024, 1024)
data:
[[[494 487 483 ... 489 504 510]
  [484 485 503 ... 491 508 486]
  [495 503 491 ... 459 489 504]
  ...
  [497 564 520 ... 472 475 473]
  [506 500 490 ... 518 516 495]
  [536 522 516 ... 507 510 506]]

 [[508 517 510 ... 494 513 499]
  [505 513 493 ... 491 509 510]
  [523 540 512 ... 515 532 522]
  ...
  [492 536 513 ... 484 484 503]
  [526 510 493 ... 491 510 513]
  [512 491 497 ... 515 530 525]]

 [[502 490 450 ... 511 502 513]
  [510 512 510 ... 476 470 500]
  [490 503 480 ... 493 504 489]
  ...
  [497 491 477 ... 515 532 521]
  [529 517 485 ... 476 472 486]
  [542 538 552 ... 497 554 491]]

 ...

 [[499 485 503 ... 470 477 498]
  [497 509 528 ... 497 507 504]
  [511 517 507 ... 520 507 466]
  ...
  [524 523 521 ... 512 534 492]
  [500 493 541 ... 497 477 474]
  [545 504 518 ... 525 514 533]]

 [[507 495 472 ... 493 512 490]
  [528 496 479 ... 487 479 488]
  [483 494 494 ... 538 509 473]
  ...
  [479 539 528 ... 510 473 494]
  [504 475 514 ... 502 488 479

In [14]:
# close the tiff file
reader.cleanup()