In [34]:
import numpy as np

import endocytosis.io.image.image_reader as image_reader
import endocytosis.contrib.gohlke.tifffile as tifffile

In [2]:
path = r'C:\Users\v\Anaconda3\envs\tensorflow\projects\imagej\2016-12-14 Sp57 proto +050 001\image.ome.tif'

In [3]:
# instantiate ImageReader
reader = image_reader.ImageReader()

In [4]:
# once load() method is executed, image data and metadata
# can be accessed via the data and metadata attributes, respectively
reader.load(path)

None


In [5]:
# select mage metadata
md = reader.metadata
reader.cleanup()

In [6]:
print(reader.is_imagej, reader.is_ome, reader.is_nih)

False True False


In [58]:
keep = ('DimensionOrder', )
print(md['Image']['Pixels'].keys())
for k, v in md['Image']['Pixels'].items():
    if not k in ('Channel', 'TiffData', 'ID', 'Type'):
        print(k, v)

dict_keys(['Channel', 'TiffData', 'DimensionOrder', 'ID', 'PhysicalSizeX', 'PhysicalSizeXUnit', 'PhysicalSizeY', 'PhysicalSizeYUnit', 'PhysicalSizeZ', 'PhysicalSizeZUnit', 'SizeC', 'SizeT', 'SizeX', 'SizeY', 'SizeZ', 'TimeIncrement', 'TimeIncrementUnit', 'Type'])
DimensionOrder XYCZT
PhysicalSizeX 0.13000013000013
PhysicalSizeXUnit µm
PhysicalSizeY 0.13000013000013
PhysicalSizeYUnit µm
PhysicalSizeZ 0.13000013000013
PhysicalSizeZUnit µm
SizeC 1
SizeT 61
SizeX 1024
SizeY 1024
SizeZ 1
TimeIncrement 0.9953396320343018
TimeIncrementUnit s


In [35]:
im = None
with tifffile.TiffFile(path) as f: 
    im = f.asarray()

In [38]:
with tifffile.TiffWriter(r"C:\Users\v\Anaconda3\envs\tensorflow\projects\imagej\2016-12-14 Sp57 proto +050 001\gohlke.tif") as f:
    f.save(im)

In [44]:
f = tifffile.TiffFile(r"C:\Users\v\Anaconda3\envs\tensorflow\projects\imagej\2016-12-14 Sp57 proto +050 001\gohlke.tif")

In [48]:
f.pages[0].__dict__

{'parent': <endocytosis.contrib.gohlke.tifffile.TiffFile at 0x214ca1374e0>,
 'index': 0,
 'shape': (1024, 1024),
 '_shape': (1, 1, 1, 1024, 1024, 1),
 'dtype': dtype('float32'),
 '_dtype': dtype('float32'),
 'axes': 'YX',
 'tags': {'NewSubfileType': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171d68>,
  'ImageWidth': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171ef8>,
  'ImageLength': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171e08>,
  'BitsPerSample': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171c78>,
  'Compression': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171cc8>,
  'PhotometricInterpretation': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171bd8>,
  'ImageDescription': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171c28>,
  'StripOffsets': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171b88>,
  'SamplesPerPixel': <endocytosis.contrib.gohlke.tifffile.TiffTag at 0x214ca171a98>,
  'RowsPerStr

In [52]:
for k, v in f.pages[0].tags.items():
    print("{}: {}".format(k, v))

NewSubfileType: TiffTag 254 NewSubfileType  1I @222  0
ImageWidth: TiffTag 256 ImageWidth  1I @222  1024
ImageLength: TiffTag 257 ImageLength  1I @222  1024
BitsPerSample: TiffTag 258 BitsPerSample  1H @222  32
Compression: TiffTag 259 Compression  1H @222  NONE
PhotometricInterpretation: TiffTag 262 PhotometricInterpretation  1H @222  MINISBLACK
ImageDescription: TiffTag 270 ImageDescription  28s @218  {"shape": [61, 1024, 1024]}
StripOffsets: TiffTag 273 StripOffsets  1I @254  (368,)
SamplesPerPixel: TiffTag 277 SamplesPerPixel  1H @254  1
RowsPerStrip: TiffTag 278 RowsPerStrip  1I @254  1024
StripByteCounts: TiffTag 279 StripByteCounts  1I @254  (4194304,)
XResolution: TiffTag 282 XResolution  2I @310  (1, 1)
YResolution: TiffTag 283 YResolution  2I @318  (1, 1)
ResolutionUnit: TiffTag 296 ResolutionUnit  1H @334  NONE
Software: TiffTag 305 Software  12s @326  tifffile.py
DateTime: TiffTag 306 DateTime  20s @338  2018:08:18 17:27:23
SampleFormat: TiffTag 339 SampleFormat  1H @366  I

In [ ]:
f.

In [8]:
# image data is retrieved as np.ndarray via the request() method of the datasource
# arguments must be listed in c, t, z order

# single image
arg = (0, 10, 5)
print("shape: {}".format(reader.data.request(*arg).shape))
print("data: {}".format(reader.data.request(*arg)))

AttributeError: 'ImageReader' object has no attribute 'data'

In [7]:
# if no parameters are entered into the .request() method, 
# simply retrieve the last requested image
# (tifffile caches these images)
print("shape: {}".format(reader.data.request().shape))
print("data:\n{}".format(reader.data.request()))

shape: (1024, 1024)
data:
[[576 519 506 ... 521 482 483]
 [516 545 550 ... 522 512 502]
 [532 487 552 ... 521 492 490]
 ...
 [504 484 495 ... 503 506 497]
 [485 488 529 ... 502 520 508]
 [511 522 583 ... 516 512 492]]


In [8]:
# use a slice argument to get a stack of images
# currently only slicing in one dimension is supported
arg = (0, slice(10), 5)
print("shape: {}".format(reader.data.request(*arg).shape))
print("data:\n{}".format(reader.data.request(*arg)))
print("page indices: {}".format(reader.data._request(0, slice(20), 5)[0]))

shape: (10, 1024, 1024)
data:
[[[599 696 511 ... 523 528 502]
  [671 551 561 ... 497 509 496]
  [585 585 578 ... 497 499 527]
  ...
  [517 508 523 ... 515 504 472]
  [501 502 500 ... 582 545 499]
  [496 500 497 ... 505 507 493]]

 [[636 570 610 ... 496 506 503]
  [627 620 519 ... 528 475 486]
  [546 569 549 ... 493 473 498]
  ...
  [512 493 507 ... 497 492 522]
  [507 512 501 ... 492 494 475]
  [544 528 515 ... 501 519 521]]

 [[701 622 503 ... 486 494 498]
  [523 557 498 ... 521 500 499]
  [535 532 585 ... 513 491 483]
  ...
  [555 501 474 ... 546 526 514]
  [479 496 514 ... 503 545 503]
  [497 504 510 ... 502 492 488]]

 ...

 [[576 701 555 ... 499 503 521]
  [660 594 647 ... 497 510 511]
  [555 606 620 ... 523 497 489]
  ...
  [553 507 505 ... 500 514 511]
  [521 555 516 ... 528 517 531]
  [502 506 510 ... 533 531 554]]

 [[537 637 613 ... 496 520 497]
  [520 553 627 ... 496 493 539]
  [594 567 585 ... 505 487 482]
  ...
  [479 463 503 ... 488 514 519]
  [498 500 499 ... 573 515 536

In [9]:
# close the tiff file
reader.cleanup()

In [53]:
class A(object):
    def __init__(self):
        self.data = {'a': 1, 'b': 2}
    
    def __getitem__(self, key):
        
        return self.data[key]

    def __missing__(self, key):
        self[key] = {}
        return self[key]

    def __setitem__(self, key, value):
        self.data[key] = value

In [54]:
a = A()

In [55]:
a['k']

KeyError: 'k'

In [59]:
[0] - np.array((5,))

array([-5])